# Use official Node.js runtime
FROM node:20

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy the rest of the code
COPY . .

# Build NestJS (if you commit only TS)
RUN npm run build

# Expose port
EXPOSE 8080

# Run app
CMD ["node", "dist/main.js"]
